- name: Setup Homeassistant RPi
  hosts: hassiopi
  gather_facts: no
  remote_user: steven
  vars_files:
    - host_vars/hassio-pi.yml

  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: true
      cache_valid_time: 3600
    become: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist
    become: yes

  - name: Install required packages
    apt:
      name: 
      - git
      - build-essential
      - python3-distutils
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - libsqlite3-dev
      - ffmpeg
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff5
      state: latest
    become: yes

  - name: Configure Python 3.8.6
    shell: |
      wget https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tar.xz
      tar xf Python-3.8.6.tar.xz
      cd Python-3.8.6
      ./configure --prefix=/usr/local/opt/python-3.8.6
    become: yes

  - name: Build & Install Python 3.8.6
    shell: |
      cd Python-3.8.6
      make -j 4
      make altinstall
    args:
      warn: no
    become: yes

  - name: Clean Up Python 3.8.6 Install
    file:
      path: /home/steven/Python-3*
      state: absent
    become: yes

  - name: Clone the PlantBud repo
    git:
      repo: 'https://github.com/steven-pilger/PlantBud'
      dest: /home/steven/PlantBud

  - name: Add Homeassistant user
    user:
      name: homeassistant
      shell: /bin/bash
      groups: dialout,gpio,i2c
      system: yes
      append: yes
    become: yes

  - name: Prepare Homeassistant Installation
    shell: |
      mkdir -p /srv/homeassistant
      cd /srv/homeassistant
      /usr/local/opt/python-3.8.6/bin/python3.8 -m venv .
      chown -R homeassistant:homeassistant /srv/homeassistant
    args:
      warn: no
    become: yes

  - name: Prepare Homeassistant virtual environment
    shell: |
      sudo -u homeassistant -H -s /srv/homeassistant/bin/python3 -m pip install wheel
    args:
      warn: no

  - name: Install/Upgrade Homeassistant
    shell: |
      sudo -u homeassistant -H -s /srv/homeassistant/bin/python3 -m pip install --upgrade homeassistant
    args:
      warn: no
    tags: hassio

  - name: Copy over systemd entry
    copy:
      src: "hassio-pi/home-assistant@homeassistant.service"
      dest: "/etc/systemd/system/home-assistant@homeassistant.service"
      mode: preserve
    become: yes

  - name: Enable and Restart HomeAssistant
    service:
      name: home-assistant@homeassistant
      state: restarted
      enabled: yes
      masked: no
    become: yes
  
  # - name: Enable and Restart HomeAssistant
  #   command: sudo -u homeassistant -H -s /srv/homeassistant/bin/hass -c /home/homeassistant/.homeassistant
