- name: Setup NodeRED RPi
  hosts: noderedpi
  gather_facts: no
  remote_user: steven
  vars_files:
    - host_vars/node-red-pi.yml

  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: true
      cache_valid_time: 3600
    become: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist
    become: yes

  - name: Set timezone Europe/Copenhagen
    command: timedatectl set-timezone Europe/Copenhagen
    become: yes

  - name: Install required packages
    apt:
      name:
      - git
      - build-essential
      - picocom
      - python3-distutils
      state: latest
    become: yes

  - name: Install pip
    shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py && rm get-pip.py

  - name: Install Ampy
    shell: python -m pip install adafruit-ampy

  - name: Add the local python bin dir to system-wide $PATH.
    copy:
      dest: /etc/profile.d/python-module-path.sh
      content: 'PATH=$PATH:~/.local/bin'
    become: yes

  - name: Clone the PlantBud repo
    git:
      repo: 'https://github.com/steven-pilger/PlantBud'
      dest: /home/steven/PlantBud

  - name: Install NodeRED
    shell: bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --confirm-root --confirm-install --confirm-pi
    args:
      executable: /bin/bash
    become: yes

  - name: Add steven user to dialout group
    user:
      name: steven
      groups: dialout
      append: yes

  - name: Add NodeRED user
    user:
      name: nodered
      shell: /bin/bash
      groups: dialout,gpio,i2c
      system: yes
      append: yes
    become: yes

  - name: Copy over systemd entry
    copy:
      src: "node-red-pi/node-red@nodered.service"
      dest: "/etc/systemd/system/node-red@nodered.service"
      mode: preserve
    become: yes

  - name: Enable and Restart NodeRED
    service:
      name: node-red@nodered.service
      state: restarted
      enabled: yes
      masked: no
    become: yes

  - name: Copy NodeRED configuration from repo to dir
    copy:
      src: "/home/steven/PlantBud/node-red-pi/{{item}}"
      dest: "{{dest_path}}/{{item}}"
      mode: preserve
      remote_src: yes
    with_items:
      - "{{configuration_files}}"
    become: yes
