# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  commit_interval: 30

lovelace:
  mode: storage
  dashboards:
      dash-home:
        mode: yaml
        title: Home
        filename: dash-home.yaml
        icon: mdi:home
      dash-plants:
        mode: yaml
        title: Plants
        filename: dash-plants.yaml
        icon: mdi:sprout

influxdb:
  api_version: 2
  host: eu-central-1-1.aws.cloud2.influxdata.com
  organization: !secret influxdb_organization_id
  token: !secret influxdb_token
  bucket: plantbud-iot
  exclude:
    entity_globs: "*"

sensor:
  - platform: influxdb
    api_version: 2
    host: eu-central-1-1.aws.cloud2.influxdata.com
    organization: !secret influxdb_organization_id
    token: !secret influxdb_token
    bucket: plantbud-iot
    queries_flux:
      - name: "Dummy Alman Temperature over Past Hour"
        range_start: "-1h"
        group_function: mean
        value_template: '{{ value | float | round(2) }}'
        unit_of_measurement: '°C'
        query: >
          filter(fn: (r) => r["_measurement"] == "test")
          |> filter(fn: (r) => r["_field"] == "temperature")
          |> filter(fn: (r) => r["device"] == "device1")
          |> keep(columns: ["_value"])
      - name: "Dummy Alman Humidity over Past Hour"
        range_start: "-1h"
        group_function: mean
        value_template: '{{ value | int }}'
        unit_of_measurement: '%'
        query: >
          filter(fn: (r) => r["_measurement"] == "test")
          |> filter(fn: (r) => r["_field"] == "humidity")
          |> filter(fn: (r) => r["device"] == "device1")
          |> keep(columns: ["_value"])

plant:
  alman:
    sensors:
      moisture: sensor.dummy_alman_humidity_over_past_hour
      # battery: sensor.my_sensor_battery
      temperature: sensor.dummy_alman_temperature_over_past_hour
      # conductivity: sensor.my_sensor_conductivity
      # brightness: sensor.my_sensor_brightness

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
