- hosts: hassiopi
  become: yes
  gather_facts: no
  remote_user: steven
  vars_files:
    - ../host_vars/hassio-pi.yml

  tasks:
  - name: Update git repo
    git: force=yes dest=~/PlantBud repo=https://github.com/steven-pilger/PlantBud
    tags: update

  - name: Copy configuration files to remote
    copy:
      src: "{{inventory_dir}}/hassio-pi/{{item}}"
      dest: "{{dest_path}}/{{item}}"
      mode: preserve
    with_items:
      - "{{configuration_files}}"
    tags: config_update

  - name: Check configuration
    command: sudo -u homeassistant -H -s /srv/homeassistant/bin/hass --script check_config --secrets
    args:
      warn: no
    tags: config_update

  - name: Enable and Restart HomeAssistant
    service:
      name: home-assistant@homeassistant
      state: restarted
      daemon_reload: yes
    become: yes
    tags: config_update
