- hosts: noderedpi
  become: yes
  gather_facts: no
  remote_user: steven
  vars_files:
    - ../host_vars/node-red-pi.yml

  tasks:
  - name: Update git repo
    git: force=yes dest=~/PlantBud repo=https://github.com/steven-pilger/PlantBud
    tags: update

  - name: Flash Probe
    command: make upload reset
    args:
      chdir: ~/PlantBud/iot-probes
    tags: flash

  - name: Copy configuration files to remote
    copy:
      src: "{{inventory_dir}}/node-red-pi/{{item}}"
      dest: "{{dest_path}}/{{item}}"
      mode: preserve
    with_items:
      - "{{configuration_files}}"
    tags: config_update
  
  - name: Enable and Restart NodeRED
    service:
      name: node-red@nodered.service
      state: restarted
      daemon_reload: yes
    become: yes
    tags: config_update
  
  - name: Pull configuration from remote to local
    fetch:
      src: "{{dest_path}}/{{item}}"
      dest: "{{inventory_dir}}/node-red-pi/{{item}}"
      flat: yes
    with_items:
      - "{{configuration_files}}"
    tags: config_pull
